### ISSUE TITLE
Les images ne sont pas visibles dans beaucoup de lecteurs RSS

### ISSUE THREAD

**Issue by rik** [notabene/nota-bene.org-squelettes#17]
Le support de `<enclosure>` est très différent d'un lecteur à l'autre. Beaucoup de lecteurs RSS n'affichent pas les images.

**Comment by notabene** [comment]
C'est lié à mon moteur (SPIP), je vais faire remonter à Spip-dev.

**Comment by notabene** [comment]
J'ai fait un ajout dans le RSS, est-ce que ça corrige ton problème @rik ?

**Comment by rik** [comment]
Je ne crois pas: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnota-bene.org%2Fspip.php%3Fpage%3Drss2

En particulier, je crois qu'une partie de la syntaxe SPIP se retrouve dans le RSS : `(oui|=={oui}|?{' ',''})<content:encoded>&lt;div class='rss_texte'&gt;&lt;p&gt;With the help of my good friend Serendipity, I was reading some backlog on Dave Winer's scripting.com when I stumbled upon this article from the Guardian:&lt;/p&gt;`

**Comment by notabene** [comment]
Haha mais c'est rigolo ça.

Le rss2 est une _legacy_ de mes anciens squelettes, je viens de pousser un nouveau squelette qui redirige de `rss2` vers `backend`. _Cool URIs don't change_, etc.

Je viens de pousser un correctif.

Par ailleurs, avant que tu ne le voies :wink: , backend renvoie aussi des erreurs au validateur, mais parce qu'il est chatouilleux (il veut du http et pas du https, et il me prévient que si je veux être hyper intéropérable je devrais changer des guillemets).

Dis-moi si avec `backend` la vie est plus belle ?

**Comment by rik** [comment]
Effectivement, plus d'erreurs de ce genre. Par contre, mon lecteur RSS ne me montre que les 2 derniers articles. Je ne sais pas si c'est lié à une erreur ou parce que les autres articles sont vieux de plus de 2 semaines. Attendons la prochaine photo publiée pour voir ce que ça donne ?
