### ISSUE TITLE
St(é)phane

### ISSUE THREAD

**Issue by benchti** [notabene/nota-bene.org-squelettes#21]
Dans mon lecteur RSS (thunderbird) 
![selection_596](https://user-images.githubusercontent.com/663816/34327732-86c8fa12-e8cc-11e7-9ac6-9ae7011c981a.png)

**Comment by notabene** [comment]
@benchti j'ai saisi mon prénom à nouveau, est-ce que ça corrige le truc ?

(j'avoue que quoi qu'il arrive je ne sais pas le corriger - fonction de base de spip à laquelle je n'ai pas touché)

**Comment by benchti** [comment]
reping moi au prochain article que je vérifie

**Comment by notabene** [comment]
@benchti ping :)

**Comment by benchti** [comment]
toujours pareil ... bon on va dire que c'est mon lecteur qui est naze tu peux fermer ;)
